
from enum import Enum

class BlockType(Enum):
    PARAGRAPH = "PARAGRAPH"
    HEADING1 = "HEADING1"
    HEADING2 = "HEADING2"
    HEADING3 = "HEADING3"
    HEADING4 = "HEADING4"
    HEADING5 = "HEADING5"
    HEADING6 = "HEADING6"

    CODE = "CODE"
    QUOTE = "QUOTE"
    UNORDEREDLIST = "UNORDEREDLIST"
    ORDEREDLIST = "ORDEREDLIST"



